- hosts: all
  tasks:
    - name: say hello
      shell: echo "Hello"

- hosts: nexus
  roles:
  - role: ansible-role-java
    become: yes
    when: "ansible_os_family == 'Debian'"
    java_packages:
      - openjdk-8-jdk
  - { role: ansible-nexus,
      nexus_version: '3.0.0-03',
      nexus_port: 9090,
      become: yes}

- hosts: elk
  become: yes
  roles:
  - role: ansible-role-java
    when: "ansible_os_family == 'Debian'"
    java_packages:
       - openjdk-8-jdk
  - ansible-elasticsearch
  - logstash-role
  - ansible-kibana


- hosts: atto-server
  roles:
  - role: ansible-role-java
    become: yes
    when: "ansible_os_family == 'Debian'"
    java_packages:
      - openjdk-8-jdk
  - { role: ansible-rapidpm-microservice,
      maven_artifact_id: "server",
      maven_group_id: "org.rapidpm.test.atto",
      nexus_ip: "10.1.1.3",
      nexus_port: "9090",
      become: yes
    }
  - { role: ansible-role-elk-filebeat,
      become: yes
    }


- hosts: atto-servicelocator
  roles:
  - role: ansible-role-java
    become: yes
    when: "ansible_os_family == 'Debian'"
    java_packages:
      - openjdk-8-jdk
  - { role: ansible-rapidpm-microservice,
      maven_artifact_id: "servicelocator-service",
      maven_group_id: "org.rapidpm.test.atto",
      nexus_ip: "10.1.1.3",
      nexus_port: "9090",
      microservice_rest_port: "9999",
      become: yes}
  - { role: ansible-role-elk-filebeat,
      become: yes
    }

