logstash_version: 2.3
logstash_defaults: |
        LS_USER=root
        LS_GROUP=root
        LS_HEAP_SIZE="256m"
logstash_inputs: |
 file {
    path => ["/vagrant/include/example-logs/testlog"]
    start_position => "beginning"
    codec => "json"
    type => "json"
  }
  beats {
      port => 5044
      type => log4j
    }
    log4j {
       mode => "server"
       host  => "0.0.0.0"
       port => 5000
       type => "log4j"
    }
logstash_filters: |
logstash_outputs: |
 file {
    path => "/var/log/logstash/output.log"
    }
 elasticsearch {
    document_type => "log4j"
    hosts => "127.0.0.1"
  }